apiVersion: v1
kind: Namespace
metadata:
  name: ms-frontend
  labels:
    name: ms-frontend
---
apiVersion: v1
kind: Service
metadata:
  name: front-gateway
  labels:
    name: front-gateway
spec:
  selector:
    name: front-gateway
  type: NodePort
  ports:
   - port: 8000
     name: http
     targetPort: 8000
     protocol: TCP
     nodePort: 32767
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-gateway
  namespace: ms-frontend
  labels:
    name: front-gateway
spec:
  selector:
    matchLabels:
      name: front-gateway
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: front-gateway
    spec:
      containers:
        - name: front-gateway
          image: vvamzy/front_gateway
          ports:
            - containerPort: 8000
              protocol: TCP
